@startuml UseCases_Invoices

skinparam style strictuml
left to right direction

actor Client as C

rectangle "Invoices" {
    usecase "List orders" as LOrd
    usecase "Select order" as SelOrd
    usecase "Select invoice" as SelInv
    usecase "List invoices" as SInv
    usecase "New Order" as NewOrd
    usecase "Manage lines" as MLines
    usecase "Add Product" as AddProd
    usecase "Edit Line" as ELine
    usecase "Change Status" as ChStatus
    usecase "Download Invoice" as DPdf
}

C --> LOrd
LOrd --> SelOrd
C --> SInv
SInv --> SelInv

SelOrd <|.. NewOrd : extends
SelOrd <|.. ChStatus : extends
NewOrd <|.. AddProd : extends
NewOrd <|.. ELine : extends
ELine <|.. MLines : extends


SelInv <|.. ChStatus : extends
SelInv <|.. DPdf : extends

@enduml