@startuml UseCases_Invoices

skinparam style strictuml
left to right direction

actor Client as C

rectangle "Invoices" {
    usecase "List orders" as LOrd
    usecase "See invoices" as SInv
    usecase "New Order" as NewOrd
    usecase "Add Product" as AddProd
    usecase "Edit Line" as ELine
    usecase "Save" as Save
    usecase "Change Status" as ChStatus
    usecase "Download Invoice" as DPdf
}

C --> LOrd
C --> SInv

LOrd ..|> NewOrd : include
LOrd ..|> ChStatus : include
NewOrd ..|> AddProd : include
NewOrd ..|> ELine : extend
AddProd ..|> Save : include
ELine ..|> Save : include

SInv ..|> ChStatus : include
SInv ..|> DPdf : include

@enduml